[package]
name = "validator-client"
version = "0.1.0"
authors = ["Jędrzej Stuczyński <andrew@nymtech.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
base64 = "0.13"
bip39 = { version = "1", features = ["rand"] }
cosmos_sdk = { git = "https://github.com/cosmos/cosmos-rust/", commit="4299b75a5a9b68e4f9a1693bb689874561d544db", features = ["rpc", "bip32", "cosmwasm"] }
mixnet-contract = { path="../../../common/mixnet-contract" }
serde = { version="1", features=["derive"] }
serde_json = "1"
rand = "0.8"
reqwest = { version="0.11", features=["json"] }
thiserror = "1"
log = "0.4"
url = "2"
wasm-timer = "0.2"
prost = { version = "0.7", default-features = false }
flate2 = "1.0.20"
sha2 = "0.9.5"
cosmwasm-std = { git = "https://github.com/jstuczyn/cosmwasm", branch="0.14.1-updatedk256" }
itertools = "0.10"

[dev-dependencies]
tokio = {version = "1.5", features = ["full"]}

[target."cfg(target_arch = \"wasm32\")".dependencies.getrandom]
version = "0.2"
optional = true

[features]
# the reason for introducing additional features is to let cargo know we don't want anything to do with "getrandom/js"
# by default as it messes up with cyclic dependencies for ahash that's indirectly used by sqlx in validator-api
wasm = ["getrandom/js"]
