[package]
name = "validator-client"
version = "0.1.0"
authors = ["Jędrzej Stuczyński <andrew@nymtech.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
base64 = "0.13"
bip39 = { version = "1", features = ["rand"] }
cosmos_sdk = { git = "https://github.com/cosmos/cosmos-rust/", commit="4299b75a5a9b68e4f9a1693bb689874561d544db", features = ["rpc", "bip32", "cosmwasm"] }
mixnet-contract = { path="../../../common/mixnet-contract" }
serde = { version="1", features=["derive"] }
serde_json = "1"
rand = "0.8"
reqwest = { version="0.11", features=["json"] }
thiserror = "1"
log = "0.4"
url = "2"
wasm-timer = "0.2"
prost = { version = "0.7", default-features = false }

[dev-dependencies]
tokio = {version = "1.5", features = ["full"]}

[target.'cfg(target_env = "wasm32-unknown-unknown")'.dependencies]
getrandom = { version="0.2", features=["js"] }
